### ISSUE TITLE
UI Mods CSS 

### ISSUE THREAD

**Issue by ComplexRobot** [anapnoe/sd-webui-ux#7]
Some features that will hopefully be added eventually, but I made some quick css mods to add them.
To use this, you add the code to the `user.css` in the root folder of the web ui. (Then reload the UI.)

Wasn't sure where to post it, but hopefully someone finds it useful. Also, I'm sure the workspaces makes this easier. 😆

Card descriptions (checkpoint, lora, TI) show only on hovering the name:
```css
.card > .actions {
    z-index: 2;
}

.card .actions:not(:hover) .description {
    max-height: 0;
    overflow: hidden;
}

.card .actions:hover .name {
    display: unset;
    overflow: unset;
    max-height: unset;
}
```

Merge prompts and basic generation parameters into a single tab:
```css
#layout-txt2img:has(#txt2img_prompts.active) *:is(#txt2img_prompts_tabitem, #txt2img_params_tabitem_group) {
    position: relative;
}

#layout-txt2img:has(#txt2img_prompts.active) #txt2img_params_tabitem_group {
    display: flex !important;
}

#layout-txt2img:has(#txt2img_prompts.active) #txt2img_prompts_tabitem {
    height: 500px;
    resize: vertical;
}

#layout-txt2img:has(#txt2img_prompts.active) #txt2img_params_tabitem {
    animation: none;
    display: block !important;
    overflow: visible;
}

#txt2img_params {
    display: none;
}
```

Fully vertical layout. Useful if you're using the web ui in a vertical/portrait view.
Could be a bit buggy, had to replace the "gutter" in the middle with a simple drag arrow in the corner. Overall, pretty hacky. I tested it thoroughly, but there seems to be some slight button-click area errors (extension tabs and reload web ui button) in a couple places. No idea why.

Looks like this:
![{575B9596-6AF4-45F5-A211-244A3711B07D}](https://github.com/user-attachments/assets/dbc86d5b-c1ea-4160-9a42-1d7fe3e88a95)

The code:
```css
#anapnoe_app {
    min-height: unset;
    width: unset;
    min-width: 100vw;
    height: 100%;
}

#main_wrapper, #accordion-aside, #split-app {
    flex-direction: column;
}

#main-nav {
    margin-right: calc(var(--ae-panel-padding)* 2) !important;
    margin-bottom: calc(var(--ae-panel-padding)* -1) !important;
}

#split-app {
    margin-left: var(--ae-panel-padding);
    margin-right: var(--ae-panel-padding);
}

#main-nav, #main-nav *, .accordion-bar * {
    flex-direction: row !important;
}

.accordion-bar {
    flex-direction: row-reverse !important;
}

#main-nav-bar, #sidebar_extra_networks, #sidebar_tabs {
    justify-content: flex-start !important;
}

.accordion-bar {
    min-height: var(--ae-input-height) !important;
}

#acc-arrow-button {
    width: unset !important;
    height: 100%;
}

.accordion-container {
    height: unset !important;
    min-height: unset !important;
    width: 100%;
    min-width: 100%;
    overflow-x: auto !important;
    overflow-y: hidden !important;
}

#split-right:not(.v-expand) #accordion-aside {
    margin-left: calc(var(--ae-border-size) * 2);
    margin-right: var(--ae-border-size);
}

#split-right:not(.v-expand) {
    min-width: unset !important;
    min-height: calc(var(--ae-input-height) + var(--ae-border-size) + (var(--ae-panel-padding) + var(--ae-input-padding)) * 2 + 1px);
}

#split-right {
    min-width: unset !important;
    flex-basis: unset !important;
    display: flex;
    flex-grow: 1;
}

#split-right.v-expand {
    min-height: calc(var(--ae-input-height) + var(--ae-border-size) + (var(--ae-panel-padding) + var(--ae-input-padding)) * 2 + 1px) !important;
    flex-grow: 0;
}

.accordion-icon {
    transform: rotate(180deg) !important;
}

.accordion-vertical.expand .accordion-icon {
    transform: rotate(0deg) !important;
}

#split-app > .gutter {
    display: none;
}

#split-left > *:is(*:not(.hidden):has(> *:not(.hidden)), .fade-in, *:has(> .fade-in)):not(#popup_tabitem) {
    position: relative;
    width: 100%;
    height: 100%;
}

#split-left > *:not(#popup_tabitem) > * {
    position: relative;
    max-height: 100%;
    flex-basis: unset;
    overflow-y: auto;
    height: 800px;
}

#split-left:not(*:has(~ #split-right.v-expand)) > *:not(#popup_tabitem) > * {
    resize: vertical;
}

#split-left:has(~ #split-right.v-expand) > *:not(#popup_tabitem) > * {
    height: 100% !important;
}

#split-left {
    flex-basis: unset !important;
    display: flex;
    flex-shrink: 1;
}

#split-left:has(~ #split-right.v-expand) {
    flex: 1 0;
}
```
